# Look for the different tagged releases at https://hub.docker.com/r/library/node/tags/
image: node:lts

before_script:
- npm install
lint:
  script:
  - npm run lint
build:
  script:
  - npm run build-ci
  